name: tigerwest/slack-approval
description: Custom action to send approval request to Slack from Github, allowing only specified approvers
author: Beom
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: check-circle
  color: orange

inputs:
  baseMessageTs:
    description: target message ts
  approvers:
    description: "A comma-separated list of approvers' slack user ids"
    required: true
    default: ""
  minimumApprovalCount:
    description: "The minimum number of approvals required"
    required: false
    default: "1"
  baseMessagePayload:
    description: "The base message payload to display. If not set, will use default message from README. To customize, provide Slack message payload JSON"
    required: false
    default: |
      {}
  successMessagePayload:
    description: "The message body indicating approval is success. If not set, will use baseMessagePayload."
    required: false
    default: |
      {}
  failMessagePayload:
    description: "The message body indicating approval is fail. If not set, will use baseMessagePayload."
    required: false
    default: |
      {}

outputs:
  mainMessageTs:
    description: slack main message ts
  replyMessageTs:
    description: slack reply message ts
  
  